### PR TITLE
Feature: Count Unique Users

### PR DESCRIPTION
**Pull request by refugene**
- New Stats schema entity to hold uniqueUsers value which is incremented every time a new user registers
- The stats entity is a singleton and we create it if not exists

### CODE REVIEW

**Comment by refugene** [comment]
See https://subgraph-staging.openformat.tech/subgraphs/name/open-format/mumbai/graphql?query=query+MyQuery+%7B%0A++stats%28id%3A+%22STATS_SINGLETON%22%29+%7B%0A++++id%0A++++uniqueUsers%0A++%7D%0A%7D

**Review by tinypell3ts — APPROVED** [review]
Looks great 👍

**Comment by tinypell3ts** [comment]
> See https://subgraph-staging.openformat.tech/subgraphs/name/open-format/mumbai/graphql?query=query+MyQuery+%7B%0A++stats%28id%3A+%22STATS_SINGLETON%22%29+%7B%0A++++id%0A++++uniqueUsers%0A++%7D%0A%7D


Is that number correct? 1181 feels like a lot.

**Comment by refugene** [comment]
> > See https://subgraph-staging.openformat.tech/subgraphs/name/open-format/mumbai/graphql?query=query+MyQuery+%7B%0A++stats%28id%3A+%22STATS_SINGLETON%22%29+%7B%0A++++id%0A++++uniqueUsers%0A++%7D%0A%7D
> 
> Is that number correct? 1181 feels like a lot.

New commit to check for empty user with Zero address before incrementing uniqueUsers, as proposed by @tinypell3ts

**Review by tinypell3ts — APPROVED** [review]

**Pull request merged**
